
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Aug 11 11:50:10 CEST 2025
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MAP = 39;
  public static final int DIVIDE = 25;
  public static final int INCREMENT = 42;
  public static final int CONST = 5;
  public static final int NUMCONST = 46;
  public static final int LPAREN = 14;
  public static final int CONTINUE = 32;
  public static final int INTERFACE = 7;
  public static final int DECREMENT = 43;
  public static final int MINUS = 23;
  public static final int RPAREN = 15;
  public static final int AND = 40;
  public static final int SEMICOLON = 9;
  public static final int LS = 20;
  public static final int OR = 41;
  public static final int COMMA = 13;
  public static final int CLASS = 6;
  public static final int GEQ = 19;
  public static final int PLUS = 22;
  public static final int MULTIPLY = 24;
  public static final int IF = 29;
  public static final int DOT = 45;
  public static final int EOF = 0;
  public static final int RETURN = 34;
  public static final int EQUAL = 8;
  public static final int NEW = 38;
  public static final int error = 1;
  public static final int PROGRAM = 2;
  public static final int MOD = 26;
  public static final int NEQ = 17;
  public static final int IDENT = 49;
  public static final int BREAK = 31;
  public static final int VOID = 28;
  public static final int EQ = 16;
  public static final int COLON = 44;
  public static final int UNION = 27;
  public static final int LBRACE = 3;
  public static final int ELSE = 30;
  public static final int LSQUARE = 10;
  public static final int READ = 33;
  public static final int CHARCONST = 47;
  public static final int WHILE = 37;
  public static final int RSQUARE = 11;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 48;
  public static final int EXTENDS = 12;
  public static final int LEQ = 21;
  public static final int GT = 18;
  public static final int DO = 36;
  public static final int PRINT = 35;
}

