package rs.ac.bg.etf.pp1;

import java_cup.runtime.*;
import org.apache.log4j.*;
import rs.ac.bg.etf.pp1.ast.*;


parser code {:
	boolean errorDetected;
	Logger log = Logger.getLogger(getClass());
	
	// slede redefinisani metodi za prijavu gresaka radi izmene teksta poruke
	
	public void report_fatal_error(String message, Object info) throws java.lang.Exception {
		done_parsing();
		report_error(message, info);
	}
	
	public void syntax_error(Symbol cur_token) {
		report_error("\nSintaksna greska", cur_token);
	}
	
	public void unrecovered_syntax_error(Symbol cur_token) throws java.lang.Exception {
		report_fatal_error("Fatalna greska, parsiranje se ne moze nastaviti", cur_token);
	}
	
	public void report_error(String message, Object info) {
		errorDetected = true;
		StringBuilder msg = new StringBuilder(message);
		if (info instanceof Symbol)
			msg.append(" na liniji ").append(((Symbol)info).left);
		log.error(msg.toString());
	}
:}


init with {:
	errorDetected = false;
:}


scan with {:
	Symbol s = this.getScanner().next_token();
	if (s != null && s.value != null)
		log.info(s.toString() + " " + s.value.toString());
	return s;
:}


terminal PROGRAM, LBRACE, RBRACE, CONST, CLASS, INTERFACE, EQUAL, SEMICOLON, LSQUARE, RSQUARE;
terminal EXTENDS, COMMA, LPAREN, RPAREN, EQ, NEQ, GT, GEQ, LS, LEQ, PLUS, MINUS, MULTIPLY, DIVIDE, MOD, UNION, VOID;
terminal IF, ELSE, BREAK, CONTINUE, READ, RETURN, PRINT, DO, WHILE, NEW, MAP, AND, OR, INCREMENT, DECREMENT, COLON, DOT;

terminal Integer NUMCONST;
terminal Character CHARCONST;
terminal Boolean BOOLCONST;
terminal String IDENT;

nonterminal DeclList DeclList;
nonterminal Declaration Declaration;
nonterminal ConstDecl ConstDecl;
nonterminal ConstList ConstList;
nonterminal GlobalVarDecl GlobalVarDecl;
nonterminal GlobalVarList GlobalVarList;
nonterminal Brackets Brackets;
nonterminal MethodDeclList MethodDeclList;
nonterminal FormPars FormPars;
nonterminal FormalPars FormalPars;
nonterminal LocalVarDeclList LocalVarDeclList;
nonterminal LocalVarDecl LocalVarDecl;
nonterminal LocalVarList LocalVarList;
nonterminal StatementsList StatementsList;
nonterminal Statement Statement;
nonterminal DoStart DoStart;
nonterminal IfStart IfStart;
nonterminal ElseStart ElseStart;
nonterminal ElseBranch ElseBranch;
nonterminal DoWhileBody DoWhileBody;
nonterminal ActPars ActPars;
nonterminal ActualPars ActualPars;
nonterminal Label Label;
nonterminal Assignop Assignop;
nonterminal Relop Relop;
nonterminal Addop Addop;
nonterminal Mulop Mulop;
nonterminal Setop Setop;

nonterminal rs.etf.pp1.symboltable.concepts.Obj Program, ProgName, Constant, GlobalVar, LocalVar;
nonterminal rs.etf.pp1.symboltable.concepts.Obj MethodDeclaration, MethodTypeName, MethodSignature;
nonterminal rs.etf.pp1.symboltable.concepts.Obj FormPar, Designator, DesignatorStatement;
nonterminal rs.etf.pp1.symboltable.concepts.Struct Type, ConstValue, TypeOrVoid, Expr, Factor, Term, Condition, CondTerm, CondFact;

precedence left ELSE;


Program ::= (Program) PROGRAM ProgName:P1 DeclList:D2 LBRACE MethodDeclList:M3 RBRACE {: RESULT=new Program(P1, D2, M3); RESULT.setLine(P1left); :};

ProgName ::= (ProgName) IDENT:progName {: RESULT=new ProgName(progName); RESULT.setLine(progNameleft); :};

DeclList ::= (Declarations) DeclList:D1 Declaration:D2 {: RESULT=new Declarations(D1, D2); RESULT.setLine(D1left); :}
			 |
			 (NoDeclarations) {: RESULT=new NoDeclarations(); :} /* epsilon */
			 ;

Declaration ::= (ConstDeclaration) ConstDecl:C1 {: RESULT=new ConstDeclaration(C1); RESULT.setLine(C1left); :}
				|
				(GlobalVarDeclaration) GlobalVarDecl:G1 {: RESULT=new GlobalVarDeclaration(G1); RESULT.setLine(G1left); :}
				;

ConstDecl ::= (ConstDecl) CONST Type:constType ConstList:C1 SEMICOLON {: RESULT=new ConstDecl(constType, C1); RESULT.setLine(constTypeleft); :};

ConstList ::= (ConstantsList) ConstList:C1 COMMA Constant:C2 {: RESULT=new ConstantsList(C1, C2); RESULT.setLine(C1left); :}
			  |
			  (NoConstantsList) Constant:C1 {: RESULT=new NoConstantsList(C1); RESULT.setLine(C1left); :}
			  ;
			  
Constant ::= (Constant) IDENT:constName EQUAL ConstValue:C1 {: RESULT=new Constant(constName, C1); RESULT.setLine(constNameleft); :};

ConstValue ::= (NumConst) NUMCONST:numConst {: RESULT=new NumConst(numConst); RESULT.setLine(numConstleft); :}
			   |
			   (CharConst) CHARCONST:charConst {: RESULT=new CharConst(charConst); RESULT.setLine(charConstleft); :}
			   |
			   (BoolConst) BOOLCONST:boolConst {: RESULT=new BoolConst(boolConst); RESULT.setLine(boolConstleft); :}
			   ;
			   
Type ::= (Type) IDENT:typeName {: RESULT=new Type(typeName); RESULT.setLine(typeNameleft); :};

GlobalVarDecl ::= (GlobalVarDecl) Type:globalVarType GlobalVarList:G1 SEMICOLON {: RESULT=new GlobalVarDecl(globalVarType, G1); RESULT.setLine(globalVarTypeleft); :};

GlobalVarList ::= (GlobalVarsList) GlobalVarList:G1 COMMA GlobalVar:G2 {: RESULT=new GlobalVarsList(G1, G2); RESULT.setLine(G1left); :}
				  |
				  (NoGlobalVarsList) GlobalVar:G1 {: RESULT=new NoGlobalVarsList(G1); RESULT.setLine(G1left); :}
				  ;
				  
GlobalVar ::= (GlobalVariable) IDENT:globalVarName Brackets:B1 {: RESULT=new GlobalVariable(globalVarName, B1); RESULT.setLine(globalVarNameleft); :}
			  |
			  (GlobalVariableError) error:e
			  {: parser.report_error("Greska u definiciji globalne promenljive na liniji " + eleft, null); :} {: RESULT=new GlobalVariableError(); :}
			  ;

Brackets ::= (SquareBrackets) LSQUARE RSQUARE {: RESULT=new SquareBrackets(); :}
			 |
			 (NoSquareBrackets) {: RESULT=new NoSquareBrackets(); :} /* epsilon */
			 ;
			 
MethodDeclList ::= (MethodDeclarations) MethodDeclList:M1 MethodDeclaration:M2 {: RESULT=new MethodDeclarations(M1, M2); RESULT.setLine(M1left); :}
				   |
				   (NoMethodDeclarations) {: RESULT=new NoMethodDeclarations(); :} /* epsilon */
				   ;
				   
MethodDeclaration ::= (MethodDeclaration) MethodSignature:M1 LocalVarDeclList:L2 LBRACE StatementsList:S3 RBRACE {: RESULT=new MethodDeclaration(M1, L2, S3); RESULT.setLine(M1left); :};

MethodSignature ::= (MethodSignature) MethodTypeName:M1 LPAREN FormPars:F2 RPAREN {: RESULT=new MethodSignature(M1, F2); RESULT.setLine(M1left); :};

MethodTypeName ::= (MethodTypeName) TypeOrVoid:T1 IDENT:methodName {: RESULT=new MethodTypeName(T1, methodName); RESULT.setLine(T1left); :};

TypeOrVoid ::= (FormalType) Type:T1 {: RESULT=new FormalType(T1); RESULT.setLine(T1left); :}
			   |
			   (VoidType) VOID {: RESULT=new VoidType(); :}
			   ;
			   
FormPars ::= (FormalParameters) FormalPars:F1 {: RESULT=new FormalParameters(F1); RESULT.setLine(F1left); :}
			 |
			 (NoFormalParameters) {: RESULT=new NoFormalParameters(); :} /* epsilon */
			 ;
			 
FormalPars ::= (FormParsList) FormalPars:F1 COMMA FormPar:F2 {: RESULT=new FormParsList(F1, F2); RESULT.setLine(F1left); :}
			   |
			   (NoFormParsList) FormPar:F1 {: RESULT=new NoFormParsList(F1); RESULT.setLine(F1left); :}
			   ;
			   
FormPar ::= (FormParam) Type:T1 IDENT:formParamName Brackets:B2 {: RESULT=new FormParam(T1, formParamName, B2); RESULT.setLine(T1left); :}
			|
			(FormParamError) error:e
			{: parser.report_error("Greska u deklaraciji formalnog parametra funkcije na liniji " + eleft, null); :} {: RESULT=new FormParamError(); :}
			;

LocalVarDeclList ::= (LocalVarsDeclList) LocalVarDeclList:L1 LocalVarDecl:L2 {: RESULT=new LocalVarsDeclList(L1, L2); RESULT.setLine(L1left); :}
					 |
					 (NoLocalVarsDeclList) {: RESULT=new NoLocalVarsDeclList(); :} /* epsilon */
					 ;

LocalVarDecl ::= (LocalVarDecl) Type:localVarType LocalVarList:L1 SEMICOLON {: RESULT=new LocalVarDecl(localVarType, L1); RESULT.setLine(localVarTypeleft); :};

LocalVarList ::= (LocalVarsList) LocalVarList:L1 COMMA LocalVar:L2 {: RESULT=new LocalVarsList(L1, L2); RESULT.setLine(L1left); :}
		    	 |
		    	 (NoLocalVarsList) LocalVar:L1 {: RESULT=new NoLocalVarsList(L1); RESULT.setLine(L1left); :}
		    	 ;
		    	 
LocalVar ::= (LocalVariable) IDENT:localVarName Brackets:B1 {: RESULT=new LocalVariable(localVarName, B1); RESULT.setLine(localVarNameleft); :}
			 |
			 (LocalVariableError) error:e
			 {: parser.report_error("Greska u definiciji lokalne promenljive na liniji " + eleft, null); :} {: RESULT=new LocalVariableError(); :}
			 ;

StatementsList ::= (StatementList) StatementsList:S1 Statement:S2 {: RESULT=new StatementList(S1, S2); RESULT.setLine(S1left); :}
				   |
				   (NoStatementList) {: RESULT=new NoStatementList(); :} /* epsilon */
				   ;
				   
Statement ::= (DesignatorStmt) DesignatorStatement:D1 SEMICOLON {: RESULT=new DesignatorStmt(D1); RESULT.setLine(D1left); :}
			  |
			  (IfStmt) IF LPAREN Condition:C1 IfStart:I2 Statement:S3 ElseBranch:E4 {: RESULT=new IfStmt(C1, I2, S3, E4); RESULT.setLine(C1left); :}
			  |
			  (BreakStmt) BREAK SEMICOLON {: RESULT=new BreakStmt(); :}
			  |
			  (ContinueStmt) CONTINUE SEMICOLON {: RESULT=new ContinueStmt(); :}
			  |
			  (ReturnExprStmt) RETURN Expr:E1 SEMICOLON {: RESULT=new ReturnExprStmt(E1); RESULT.setLine(E1left); :}
			  |
			  (ReturnNoExprStmt) RETURN SEMICOLON {: RESULT=new ReturnNoExprStmt(); :}
			  |
			  (ReadStmt) READ LPAREN Designator:D1 RPAREN SEMICOLON {: RESULT=new ReadStmt(D1); RESULT.setLine(D1left); :}
			  |
			  (PrintNumStmt) PRINT LPAREN Expr:E1 COMMA NUMCONST:N2 RPAREN SEMICOLON {: RESULT=new PrintNumStmt(E1, N2); RESULT.setLine(E1left); :}
			  |
			  (PrintNoNumStmt) PRINT LPAREN Expr:E1 RPAREN SEMICOLON {: RESULT=new PrintNoNumStmt(E1); RESULT.setLine(E1left); :}
			  |
			  (DoWhileStmt) DoStart:D1 Statement:S2 WHILE LPAREN DoWhileBody:D3 RPAREN SEMICOLON {: RESULT=new DoWhileStmt(D1, S2, D3); RESULT.setLine(D1left); :}
			  |
			  (Statements) LBRACE StatementsList:S1 RBRACE {: RESULT=new Statements(S1); RESULT.setLine(S1left); :}
			  ;
			  
DoStart ::= (DoStart) DO {: RESULT=new DoStart(); :};
			  
IfStart ::= (IfStart) RPAREN {: RESULT=new IfStart(); :};
			  
ElseBranch ::= (ElseStatement) ElseStart:E1 Statement:S2 {: RESULT=new ElseStatement(E1, S2); RESULT.setLine(E1left); :}
			   |
			   (NoElseStatement) {: RESULT=new NoElseStatement(); :} /* epsilon */
			   ;
			   
ElseStart ::= (ElseStart) ELSE {: RESULT=new ElseStart(); :};

DoWhileBody ::= (DoWhileCond) Condition:C1 {: RESULT=new DoWhileCond(C1); RESULT.setLine(C1left); :}
				|
				(DoWhileCondDesignator) Condition:C1 COMMA DesignatorStatement:D2 {: RESULT=new DoWhileCondDesignator(C1, D2); RESULT.setLine(C1left); :}
				|
				(NoDoWhileBody) {: RESULT=new NoDoWhileBody(); :} /* epsilon */
				;
			  
DesignatorStatement ::= (AssignDesignatorStmt) Designator:D1 Assignop:A2 Expr:expr {: RESULT=new AssignDesignatorStmt(D1, A2, expr); RESULT.setLine(D1left); :}
						|
						(ActParsDesignatorStmt) Designator:D1 LPAREN ActPars:A2 RPAREN {: RESULT=new ActParsDesignatorStmt(D1, A2); RESULT.setLine(D1left); :}
						|
						(IncrDesignatorStmt) Designator:D1 INCREMENT {: RESULT=new IncrDesignatorStmt(D1); RESULT.setLine(D1left); :}
						|
						(DecrDesignatorStmt) Designator:D1 DECREMENT {: RESULT=new DecrDesignatorStmt(D1); RESULT.setLine(D1left); :}
						|
						(SetDesignatorStmt) Designator:D1 Assignop:A2 Designator:D3 Setop:S4 Designator:D5 {: RESULT=new SetDesignatorStmt(D1, A2, D3, S4, D5); RESULT.setLine(D1left); :}
						|
						(ErrorDesignatorStatement) error:e
						{: parser.report_error("Greska u konstrukciji iskaza dodele na liniji " + eleft, null); :} {: RESULT=new ErrorDesignatorStatement(); :}
						;
						
ActPars ::= (ActualParameters) ActualPars:A1 {: RESULT=new ActualParameters(A1); RESULT.setLine(A1left); :}
			|
			(NoActualParameters) {: RESULT=new NoActualParameters(); :} /* epsilon */
			;
			
ActualPars ::= (ActParsList) ActualPars:A1 COMMA Expr:E2 {: RESULT=new ActParsList(A1, E2); RESULT.setLine(A1left); :}
			   |
			   (NoActParsList) Expr:E1 {: RESULT=new NoActParsList(E1); RESULT.setLine(E1left); :}
			   ;
						
Condition ::= (CondTermList) Condition:C1 OR CondTerm:C2 {: RESULT=new CondTermList(C1, C2); RESULT.setLine(C1left); :}
			  |
			  (NoCondTermList) CondTerm:C1 {: RESULT=new NoCondTermList(C1); RESULT.setLine(C1left); :}
			  |
			  (ConditionError) error:e
			  {: parser.report_error("Greska u logickom izrazu na liniji " + eleft, null); :} {: RESULT=new ConditionError(); :}
			  ;
			  
CondTerm ::= (CondFactList) CondTerm:C1 AND CondFact:C2 {: RESULT=new CondFactList(C1, C2); RESULT.setLine(C1left); :}
			 |
			 (NoCondFactList) CondFact:C1 {: RESULT=new NoCondFactList(C1); RESULT.setLine(C1left); :}
			 ;
			 
CondFact ::= (CondFactExpr) Expr:E1 {: RESULT=new CondFactExpr(E1); RESULT.setLine(E1left); :}
			 |
			 (CondFactRelop) Expr:E1 Relop:R2 Expr:E3 {: RESULT=new CondFactRelop(E1, R2, E3); RESULT.setLine(E1left); :}
			 ;
			 
Expr ::= (NegativeExpr) MINUS Term:T1 {: RESULT=new NegativeExpr(T1); RESULT.setLine(T1left); :}
		 |
		 (PositiveExpr) Term:T1 {: RESULT=new PositiveExpr(T1); RESULT.setLine(T1left); :}
		 |
		 (ExprList) Expr:E1 Addop:A2 Term:T3 {: RESULT=new ExprList(E1, A2, T3); RESULT.setLine(E1left); :}
		 |
		 (DesignatorExpr) Designator:D1 MAP Designator:D2 {: RESULT=new DesignatorExpr(D1, D2); RESULT.setLine(D1left); :}
		 ;
		 
Term ::= (MulopTerm) Term:T1 Mulop:M2 Factor:F3 {: RESULT=new MulopTerm(T1, M2, F3); RESULT.setLine(T1left); :}
		 |
		 (NoMulopTerm) Factor:F1 {: RESULT=new NoMulopTerm(F1); RESULT.setLine(F1left); :}
		 ;
		 
Factor ::= (FactorNoActPars) Designator:D1 {: RESULT=new FactorNoActPars(D1); RESULT.setLine(D1left); :}
		   |
		   (FactorActPars) Designator:D1 LPAREN ActPars:A2 RPAREN {: RESULT=new FactorActPars(D1, A2); RESULT.setLine(D1left); :}
		   |
		   (FactorNum) NUMCONST:numConst {: RESULT=new FactorNum(numConst); RESULT.setLine(numConstleft); :}
		   |
		   (FactorChar) CHARCONST:charConst {: RESULT=new FactorChar(charConst); RESULT.setLine(charConstleft); :}
		   |
		   (FactorBool) BOOLCONST:boolConst {: RESULT=new FactorBool(boolConst); RESULT.setLine(boolConstleft); :}
		   |
		   (FactorNewExpr) NEW Type:typeName LSQUARE Expr:E1 RSQUARE {: RESULT=new FactorNewExpr(typeName, E1); RESULT.setLine(typeNameleft); :}
		   |
		   (FactorNewActPars) NEW Type:typeName LPAREN ActPars:A1 RPAREN {: RESULT=new FactorNewActPars(typeName, A1); RESULT.setLine(typeNameleft); :}
		   |
		   (FactorExpr) LPAREN Expr:E1 RPAREN {: RESULT=new FactorExpr(E1); RESULT.setLine(E1left); :}
		   ;
		   
Designator ::= (DesignatorIdentOnly) IDENT:ident {: RESULT=new DesignatorIdentOnly(ident); RESULT.setLine(identleft); :}
			   |
			   (DesignatorWithDot) Designator:D1 DOT IDENT:ident {: RESULT=new DesignatorWithDot(D1, ident); RESULT.setLine(D1left); :}
			   |
			   (DesignatorWithExpr) Designator:D1 LSQUARE Expr:E2 RSQUARE {: RESULT=new DesignatorWithExpr(D1, E2); RESULT.setLine(D1left); :}
			   ;

Label ::= (Label) IDENT:labelName {: RESULT=new Label(labelName); RESULT.setLine(labelNameleft); :};

Assignop ::= (Assignop) EQUAL {: RESULT=new Assignop(); :};

Relop ::= (Equal) EQ {: RESULT=new Equal(); :}
		  |
		  (NotEqual) NEQ {: RESULT=new NotEqual(); :}
		  |
		  (Greater) GT {: RESULT=new Greater(); :}
		  |
		  (GreaterEqual) GEQ {: RESULT=new GreaterEqual(); :}
		  |
		  (Less) LS {: RESULT=new Less(); :}
		  |
		  (LessEqual) LEQ {: RESULT=new LessEqual(); :}
		  ;
		  
Addop ::= (Plus) PLUS {: RESULT=new Plus(); :}
		  |
		  (Minus) MINUS {: RESULT=new Minus(); :}
		  ;
		  
Mulop ::= (Multiply) MULTIPLY {: RESULT=new Multiply(); :}
		  |
		  (Divide) DIVIDE {: RESULT=new Divide(); :}
		  |
		  (Mod) MOD {: RESULT=new Mod(); :}
		  ;
		  
Setop ::= (Setop) UNION {: RESULT=new Setop(); :};
